on: [push]


jobs:
  uv-example:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: wntrblm/nox@main

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up project deps
        run: uv sync

      - name: Set up Python
        run: uv python install

      - name: Test
        run: nox -s test
